return {
  { import = "plugins.autocompletion" },
  { import = "plugins.colorscheme" },
  { import = "plugins.dashboard" },
  { import = "plugins.formatting" },
  { import = "plugins.lsp" },
  { import = "plugins.navigation" },
  { import = "plugins.statusline" },
  { import = "plugins.syntax" },
  { import = "plugins.terminal" },
  { import = "plugins.tools" },
  { import = "plugins.ui" },
  { import = "plugins.utilities" },
  { import = "plugins.github"},
}
